//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biss.EmployeeManagement.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceApp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceApp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Biss.EmployeeManagement.Domain.Resources.ResourceApp", typeof(ResourceApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee with document number &apos;{0}&apos; already exists..
        /// </summary>
        public static string EMPLOYEE_DOCUMENT_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EMPLOYEE_DOCUMENT_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee with document number &apos;{0}&apos; already exists (ID: {1})..
        /// </summary>
        public static string EMPLOYEE_DOCUMENT_ALREADY_EXISTS_WITH_ID {
            get {
                return ResourceManager.GetString("EMPLOYEE_DOCUMENT_ALREADY_EXISTS_WITH_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee with email &apos;{0}&apos; already exists..
        /// </summary>
        public static string EMPLOYEE_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EMPLOYEE_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee with email &apos;{0}&apos; already exists (ID: {1})..
        /// </summary>
        public static string EMPLOYEE_EMAIL_ALREADY_EXISTS_WITH_ID {
            get {
                return ResourceManager.GetString("EMPLOYEE_EMAIL_ALREADY_EXISTS_WITH_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee not found: {0}.
        /// </summary>
        public static string EMPLOYEE_NOT_FOUND {
            get {
                return ResourceManager.GetString("EMPLOYEE_NOT_FOUND", resourceCulture);
            }
        }
    }
}
